version: '3.9'

services:
  api:
    build: ./
    command: ./cmd/apiserver/wait-for-postgres.sh db ./billing-api
    ports:
      - 8080:8080
    depends_on:
      - db
    environment:
      - DB_PASSWORD=0000

  db:
    restart: always
    image: postgres:latest
    environment:
      - POSTGRES_PASSWORD=0000
    ports:
      - 5432:5432
    volumes:
      - ./docker_postgres_init.sql:/docker-entrypoint-initdb.d/docker_postgres_init.sql
